with open('SiatBillingSystem.API/Program.cs', 'w', encoding='utf-8') as f:
    f.write('using Microsoft.EntityFrameworkCore;\n')
    f.write('using SiatBillingSystem.Application.Interfaces;\n')
    f.write('using SiatBillingSystem.Application.Services;\n')
    f.write('using SiatBillingSystem.Infrastructure.Persistence;\n')
    f.write('using SiatBillingSystem.Infrastructure.Repositories;\n')
    f.write('using SiatBillingSystem.Infrastructure.Services;\n')
    f.write('\n')
    f.write('var builder = WebApplication.CreateBuilder(args);\n')
    f.write('\n')
    f.write('builder.Services.AddControllers();\n')
    f.write('builder.Services.AddEndpointsApiExplorer();\n')
    f.write('builder.Services.AddSwaggerGen(options =>\n')
    f.write('{\n')
    f.write('    options.SwaggerDoc("v1", new()\n')
    f.write('    {\n')
    f.write('        Title = "SIAT Billing System API",\n')
    f.write('        Version = "v1",\n')
    f.write('        Description = "API de Facturacion Electronica SIAT - Sector Servicios - Bolivia"\n')
    f.write('    });\n')
    f.write('});\n')
    f.write('\n')
    f.write('builder.Services.AddDbContext<SiatDbContext>(options =>\n')
    f.write('    options.UseSqlite(builder.Configuration.GetConnectionString("DefaultConnection")));\n')
    f.write('\n')
    f.write('builder.Services.AddScoped<ISignatureService, SignatureService>();\n')
    f.write('builder.Services.AddScoped<IInvoiceRepository, InvoiceRepository>();\n')
    f.write('builder.Services.AddScoped<IClienteRepository, ClienteRepository>();\n')
    f.write('builder.Services.AddScoped<IConfiguracionRepository, ConfiguracionRepository>();\n')
    f.write('builder.Services.AddScoped<IInvoiceService, InvoiceService>();\n')
    f.write('\n')
    f.write('builder.Services.AddCors(options =>\n')
    f.write('{\n')
    f.write('    options.AddPolicy("AllowBlazorClient", policy =>\n')
    f.write('        policy.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader());\n')
    f.write('});\n')
    f.write('\n')
    f.write('var app = builder.Build();\n')
    f.write('\n')
    f.write('if (app.Environment.IsDevelopment())\n')
    f.write('{\n')
    f.write('    app.UseSwagger();\n')
    f.write('    app.UseSwaggerUI(options =>\n')
    f.write('    {\n')
    f.write('        options.SwaggerEndpoint("/swagger/v1/swagger.json", "SIAT Billing v1");\n')
    f.write('        options.RoutePrefix = string.Empty;\n')
    f.write('    });\n')
    f.write('}\n')
    f.write('\n')
    f.write('app.UseHttpsRedirection();\n')
    f.write('app.UseCors("AllowBlazorClient");\n')
    f.write('app.UseAuthorization();\n')
    f.write('app.MapControllers();\n')
    f.write('\n')
    f.write('app.Run();\n')
print('Archivo generado correctamente')
