// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiatBillingSystem.Infrastructure.Persistence;

#nullable disable

namespace SiatBillingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(SiatDbContext))]
    [Migration("20260222192505_SeedCatalogosSin")]
    partial class SeedCatalogosSin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("SiatBillingSystem.Domain.Entities.ClienteFrecuente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoTipoDocumento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Complemento")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreRazonSocial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalFacturas")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UltimaFactura")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreRazonSocial");

                    b.HasIndex("NumeroDocumento");

                    b.ToTable("ClientesFrecuentes", (string)null);
                });

            modelBuilder.Entity("SiatBillingSystem.Domain.Entities.ConfiguracionEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActividadEconomica")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoModalidad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoPuntoVenta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoSucursal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cufd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCufd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeyendaLey453")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordCertificadoCifrado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaCertificado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("UltimoNumeroFactura")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("VencimientoCufd")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionEmpresa", (string)null);
                });

            modelBuilder.Entity("SiatBillingSystem.Domain.Entities.LeyendaFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoActividad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionLeyenda")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodigoActividad");

                    b.ToTable("LeyendasFactura", (string)null);
                });

            modelBuilder.Entity("SiatBillingSystem.Domain.Entities.MetodoPago", b =>
                {
                    b.Property<int>("CodigoClasificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CodigoClasificador");

                    b.ToTable("MetodosPago", (string)null);
                });

            modelBuilder.Entity("SiatBillingSystem.Domain.Entities.ServiceInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteFrecuenteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoAutorizacion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoMetodoPago")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoModalidad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoPuntoVenta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoSucursal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoTipoDocumentoIdentidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Complemento")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuf")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cufd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoEnvio")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaRespuestaSin")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntentosEnvio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Leyenda")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoTotalSujetoIva")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NitEmisor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreRazonSocial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("NumeroFactura")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoDocumentoSector")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoEmision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoFactura")
                        .HasColumnType("INTEGER");

                    b.Property<string>("XmlFirmado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteFrecuenteId");

                    b.HasIndex("Cuf")
                        .IsUnique();

                    b.HasIndex("EstadoEnvio");

                    b.HasIndex("FechaEmision");

                    b.HasIndex("NumeroFactura");

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("SiatBillingSystem.Domain.Entities.ServiceInvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActividadEconomica")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoProductoSin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceInvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceInvoiceId");

                    b.ToTable("DetallesFactura", (string)null);
                });

            modelBuilder.Entity("SiatBillingSystem.Domain.Entities.TipoDocumentoIdentidad", b =>
                {
                    b.Property<int>("CodigoClasificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CodigoClasificador");

                    b.ToTable("TiposDocumentoIdentidad", (string)null);
                });

            modelBuilder.Entity("SiatBillingSystem.Domain.Entities.TipoMoneda", b =>
                {
                    b.Property<int>("CodigoClasificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CodigoClasificador");

                    b.ToTable("TiposMoneda", (string)null);
                });

            modelBuilder.Entity("SiatBillingSystem.Domain.Entities.UnidadMedida", b =>
                {
                    b.Property<int>("CodigoClasificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CodigoClasificador");

                    b.ToTable("UnidadesMedida", (string)null);
                });

            modelBuilder.Entity("SiatBillingSystem.Domain.Entities.ServiceInvoice", b =>
                {
                    b.HasOne("SiatBillingSystem.Domain.Entities.ClienteFrecuente", "ClienteFrecuente")
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteFrecuenteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClienteFrecuente");
                });

            modelBuilder.Entity("SiatBillingSystem.Domain.Entities.ServiceInvoiceDetail", b =>
                {
                    b.HasOne("SiatBillingSystem.Domain.Entities.ServiceInvoice", "ServiceInvoice")
                        .WithMany("Details")
                        .HasForeignKey("ServiceInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceInvoice");
                });

            modelBuilder.Entity("SiatBillingSystem.Domain.Entities.ClienteFrecuente", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("SiatBillingSystem.Domain.Entities.ServiceInvoice", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
